wget http://wwtweb.blob.core.windows.net/images/learn/Create%20New%20Tour.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Tour%20Properties.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Add%20New%20Slide.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Slide%20Duration.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Show%20Slide%20Numbers.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Set%20End%20Camera%20Position.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Slide%20Transitions.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Overlays.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Animation%20Start.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Animation%20End.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Music.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Master%20Slide.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Save.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Connect%20with%20WWT.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/guided_tours_edit_tour.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/tour_properties.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/transition_options.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/timeline_editor_buttons.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/keyframe_properties.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/DivineVisualization%2001.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/DivineVisualization%2002.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/SetFullDome.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/DomeSetup.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/FullDomeView.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/OverlayList.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/DomePreview.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Normal%20Video%20Output.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/View-Fulldome.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/layers.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/iss_model.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/layers2.jpg
wget http://wwtweb.blob.core.windows.net/sunrisesunset.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/location_search.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/layer_mgr_new_great_circle.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/great_circle_properties.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/chicago_hawaii_earth.jpg
wget https://cloud.githubusercontent.com/assets/9676722/12967831/adecb7c6-d02f-11e5-97c7-7e484d9a4e87.jpg
wget https://cloud.githubusercontent.com/assets/9676722/12967832/adee49ce-d02f-11e5-8a08-1c7811e427a8.jpg
wget https://cloud.githubusercontent.com/assets/9676722/12967829/adec5a1a-d02f-11e5-9183-266d27b603f8.jpg
wget https://cloud.githubusercontent.com/assets/9676722/12967830/adec5dd0-d02f-11e5-8b38-e9aaffe1001f.jpg
wget https://cloud.githubusercontent.com/assets/9676722/12967828/adec3a4e-d02f-11e5-98e9-957b082eb8fd.jpg
wget https://cloud.githubusercontent.com/assets/9676722/12994470/9384419e-d0e6-11e5-804e-321bfd1514f4.jpg
wget https://cloud.githubusercontent.com/assets/9676722/12994471/93855a0c-d0e6-11e5-8886-9427016d9409.jpg
wget https://cloud.githubusercontent.com/assets/9676722/12994472/93863fd0-d0e6-11e5-81e0-0d5039bcaad7.jpg
wget https://cloud.githubusercontent.com/assets/9676722/12994469/93838470-d0e6-11e5-9bd4-c157c2e06c1d.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Guided%20Tours%20Tab.jpg
wget http://wwtweb.blob.core.windows.net/learn/newrefframe.jpg
wget http://wwtweb.blob.core.windows.net/learn/refframe_pos.jpg
wget http://wwtweb.blob.core.windows.net/learn/import_tle.jpg
wget http://wwtweb.blob.core.windows.net/learn/as_ref_frame.jpg
wget http://wwtweb.blob.core.windows.net/learn/wwt_signin.jpg
wget http://wwtweb.blob.core.windows.net/learn/signin_dialog.jpg
wget http://wwtweb.blob.core.windows.net/learn/myprofile.jpg
wget http://wwtweb.blob.core.windows.net/learn/communitytab.jpg
wget http://wwtweb.blob.core.windows.net/learn/mywwtfolder.jpg
wget http://wwtweb.blob.core.windows.net/learn/browsealltours.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Play%20Tour%20from%20List.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Play%20Loaded%20Tour.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Edit%20Tour.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Save%20Tour.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Sky_DSS.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Sky_IRAS.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/LookAtEarth.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/LookAtMars.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/LookAtPano.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/LookAtSolarSystem.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/look_at_dropdown.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/8k_cloud_textures.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/earth_core.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/image_alignment.jpg
wget http://images.ipac.caltech.edu/spitzer/sig14-022/spitzer_sig14-022_2051.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/AVM_Import.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/histogram.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/mapping_data.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/wildlife_growth.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/simbad_search.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/nvo_search_button.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/verbosity_medium.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/vo_table_viewer.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/vo_plot.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/topcat.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/topcat_scatter.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Layer%20Manager%201.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Find-Replace.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Text%20Import%201.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Text%20Import%202.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Excel%202.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/AddIn%201.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/AddIn%202.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Traverse%20Big.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Properties.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Traverse%20Thin.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/EarthandPlanet.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Olympus%20Mons.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/STL%20Dialog.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Export%20STL.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/numark_djtogo.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/numark_djtogo.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/virtual_buttons.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Anti-Aliasing.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/stereo_oculus.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Git%20Installer.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Importing%20Notebook.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Controlling%20Notebook.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Performance%20Data.jpg
wget http://wwtweb.blob.core.windows.net/images/learn/Projector%20Server%20List.jpg
